# Set C-q to <prefix>
unbind C-b
set -g prefix C-q
bind C-q send-prefix

# Split panes using | and -
unbind "%"
unbind '"'
bind | split-window -h
bind - split-window -v

# Reload config file
bind r source-file ~/.tmux.conf

# Enable mouse mode
set -g mouse on

# Disable Esc delay
set -s escape-time 0

# Start window index at 1
set -g base-index 1

# Renumber windows after deleting one
set-option -g renumber-windows on

# Use <prefix> Space to enter copy mode
bind -n C-Space copy-mode

# Copy mode bindings
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe "xclip -selection clipboard -in"
unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi C-Space send -X cancel

# # Use <prefix> (hjkl) to focus panes
# bind -r h select-pane -L
# bind -r j select-pane -D
# bind -r k select-pane -U
# bind -r l select-pane -R

# # Use <prefix> C-(hjkl) to resize panes
# bind -r C-h resize-pane -L 2
# bind -r C-j resize-pane -U 2
# bind -r C-k resize-pane -D 2
# bind -r C-l resize-pane -R 2

# Use <prefix> (hl) to swap windows
bind -r h swap-window -t -1 \; select-window -t -1
bind -r l swap-window -t +1 \; select-window -t +1

# Use <prefix> n to create new window in current directory
bind n new-window -c "#{pane_current_path}"

# Use Alt-<number> to focus windows
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
