[keyboard]
bindings = [ { key = "N", mods = "Control", command = { program = "bash", args = ["-c", "alacritty"] } }, ]

[font]
normal = { family = "Hack", style = "Regular" }
bold = { family = "Hack", style = "Bold" }
italic = { family = "Hack", style = "Italic" }
bold_italic = { family = "Hack", style = "Bold Italic" }
size = 9.0
