[keyboard]
bindings = [
    { key = "T", mods = "Control|Shift", command = { program = "bash", args = ["-c", "alacritty"] } },
    { key = "U", mods = "Control|Shift", action = "ScrollToTop" },
    { key = "D", mods = "Control|Shift", action = "ScrollToBottom" },
]

[font]
normal = { family = "Hack", style = "Regular" }
bold = { family = "Hack", style = "Bold" }
italic = { family = "Hack", style = "Italic" }
bold_italic = { family = "Hack", style = "Bold Italic" }
size = 11.0

[window]
startup_mode = "Maximized"
